[package]
name = "rust_common_features"
version = "0.1.0"
authors = ["Hans <jeremy3599@snu.ac.kr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
